# 빅데이터 분석 기사 실기 시험 준비를 위한 판다스 100제 전체 실습 환경 구성

# 데이터 다운로드 : https://cafe.daum.net/oracleoracle/Smgg/1

In [47]:
import  pandas  as  pd

#from google.colab import drive
#drive.mount('/content/drive')

#2. Google Drive에서 파일 불러오기

#from google.colab import drive
#drive.mount('/content/drive')

#df = pd.read_excel('/content/drive/MyDrive/Colab Notebooks/titanic.xlsx')
#df
#df = pd.read_excel('titanic.xlsx')


# emp20 = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/판다스100제-실습파일/emp20.csv", encoding="euckr")
# emp = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/판다스100제-실습파일/emp.csv")
# tit = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/판다스100제-실습파일/train.csv")
# dept = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/판다스100제-실습파일/dept.csv")
# boston = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/판다스100제-실습파일/boston.csv")

emp = pd.read_csv("판다스100제 실습파일/emp.csv")

In [48]:
emp

    empno   ename        job     mgr    hiredate   sal    comm  deptno
0    7839    KING  PRESIDENT     NaN  1981-11-17  5000     NaN      10
1    7698   BLAKE    MANAGER  7839.0  1981-05-01  2850     NaN      30
2    7782   CLARK    MANAGER  7839.0  1981-05-09  2450     NaN      10
3    7566   JONES    MANAGER  7839.0  1981-04-01  2975     NaN      20
4    7654  MARTIN   SALESMAN  7698.0  1981-09-10  1250  1400.0      30
5    7499   ALLEN   SALESMAN  7698.0  1981-02-11  1600   300.0      30
6    7844  TURNER   SALESMAN  7698.0  1981-08-21  1500     0.0      30
7    7900   JAMES      CLERK  7698.0  1981-12-11   950     NaN      30
8    7521    WARD   SALESMAN  7698.0  1981-02-23  1250   500.0      30
9    7902    FORD    ANALYST  7566.0  1981-12-11  3000     NaN      20
10   7369   SMITH      CLERK  7902.0  1980-12-09   800     NaN      20
11   7788   SCOTT    ANALYST  7566.0  1982-12-22  3000     NaN      20
12   7876   ADAMS      CLERK  7788.0  1983-01-15  1100     NaN      20
13   7934  MILLER      CLERK  7782.0  1982-01-11  1300     NaN      10

In [49]:
#▩ 예제2.   특정 컬럼 출력하기

# 문법:    데이터프레임명 [  ['컬럼명1', '컬럼명2' ]  ]
# emp 데이터 프레임에서 이름과 월급을 출력하세요 !

#emp = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/판다스100제-실습파일/emp.csv")

emp[ ['ename', 'sal' ]  ]

     ename   sal
0     KING  5000
1    BLAKE  2850
2    CLARK  2450
3    JONES  2975
4   MARTIN  1250
5    ALLEN  1600
6   TURNER  1500
7    JAMES   950
8     WARD  1250
9     FORD  3000
10   SMITH   800
11   SCOTT  3000
12   ADAMS  1100
13  MILLER  1300

In [50]:
emp[ ['ename', 'sal' ]  ]

     ename   sal
0     KING  5000
1    BLAKE  2850
2    CLARK  2450
3    JONES  2975
4   MARTIN  1250
5    ALLEN  1600
6   TURNER  1500
7    JAMES   950
8     WARD  1250
9     FORD  3000
10   SMITH   800
11   SCOTT  3000
12   ADAMS  1100
13  MILLER  1300

In [51]:
#문제2.    사원번호, 이름, 월급, 직업을 출력하시오 !

#답:
emp[['empno', 'ename', 'sal', 'job']]

    empno   ename   sal        job
0    7839    KING  5000  PRESIDENT
1    7698   BLAKE  2850    MANAGER
2    7782   CLARK  2450    MANAGER
3    7566   JONES  2975    MANAGER
4    7654  MARTIN  1250   SALESMAN
5    7499   ALLEN  1600   SALESMAN
6    7844  TURNER  1500   SALESMAN
7    7900   JAMES   950      CLERK
8    7521    WARD  1250   SALESMAN
9    7902    FORD  3000    ANALYST
10   7369   SMITH   800      CLERK
11   7788   SCOTT  3000    ANALYST
12   7876   ADAMS  1100      CLERK
13   7934  MILLER  1300      CLERK

In [52]:
# ▩ 예제3.  특정 검색 조건에 해당하는 데이터 검색하기

# 문법:  데이터프레임명[ ['컬럼명1', '컬럼명2'] ]  [  검색조건  ]

# 예제:    월급이 3000 인 사원들의 이름과 월급을 출력하시오

emp[ [ 'ename', 'sal' ]  ]  [  emp['sal'] == 3000 ]

    ename   sal
9    FORD  3000
11  SCOTT  3000

In [53]:
# 문제3.  직업이  SALESMAN 인 사원들의 이름과 월급과 직업을 출력하시오 !

emp[['ename', 'sal', 'job']] [ emp['job']=='SALESMAN']

    ename   sal       job
4  MARTIN  1250  SALESMAN
5   ALLEN  1600  SALESMAN
6  TURNER  1500  SALESMAN
8    WARD  1250  SALESMAN

In [54]:
# 문제4.  월급이 1200 이상인 사원들의 이름과 월급과 직업을 출력하시오 !

#답:
#emp = pd.read_csv("/content/drive/MyDrive/data100/emp.csv")

emp[['ename','sal','job']][emp['sal'] >= 1200 ]

     ename   sal        job
0     KING  5000  PRESIDENT
1    BLAKE  2850    MANAGER
2    CLARK  2450    MANAGER
3    JONES  2975    MANAGER
4   MARTIN  1250   SALESMAN
5    ALLEN  1600   SALESMAN
6   TURNER  1500   SALESMAN
8     WARD  1250   SALESMAN
9     FORD  3000    ANALYST
11   SCOTT  3000    ANALYST
13  MILLER  1300      CLERK

In [55]:
#문제5.   부서번호가 20번인 사원들의 이름과 월급과 부서번호를 출력하시오 !

#답:

emp[['ename','sal','deptno']] [ emp['deptno']==20]

    ename   sal  deptno
3   JONES  2975      20
9    FORD  3000      20
10  SMITH   800      20
11  SCOTT  3000      20
12  ADAMS  1100      20

In [56]:
# ▩ 예제4. 자주 사용하는  기타 비교 연산자 4가지

# >, <, >=, <=, ==, !=

#           SQL               vs                    판다스
# 1.  between .. and                 emp['sal'].between(1000, 3000)
# 2.  in                                       emp['deptno'].isin([ 10, 20 ] )
# 3.  is  null                              emp['comm'].isnull()
# 4.  like                                   emp['ename'].apply( lambda 함수)

In [57]:
# 문제6.   월급이 1000 에서 3000 사이인 사원들의 이름과 월급을 출력하시오 !

#답:

emp[['ename','sal']][emp['sal'].between(1000,3000)  ]

     ename   sal
1    BLAKE  2850
2    CLARK  2450
3    JONES  2975
4   MARTIN  1250
5    ALLEN  1600
6   TURNER  1500
8     WARD  1250
9     FORD  3000
11   SCOTT  3000
12   ADAMS  1100
13  MILLER  1300

In [58]:
#문제7.  월급이 1000 에서 3000 사이가 아닌 사원들의 이름과 월급을 출력하시오

#답:

emp[['ename','sal']][ ~ emp['sal'].between(1000,3000)  ]

# 판다스에서의 not 은 ~ 입니다.

    ename   sal
0    KING  5000
7   JAMES   950
10  SMITH   800


        SQL               vs                    판다스
 1.  between .. and               emp['sal'].between(1000, 3000)
 2.  in                                     emp['job'].isin([ 10, 20 ] )      
 3.  is  null                            emp['comm'].isnull()
 4.  like                                  emp['ename'].apply( lambda 함수)

  emp  <---   판다스 데이터 프레임 ( dataframe )  ,  오라클의 테이블
  emp['sal']  <---   판다스 시리즈(series) ,  오라클의 컬럼

컬럼(시리즈) 의 데이터를 잘 검색할 수  있도록 도와주는 함수들이
여러개가 있습니다.   이 중에 apply 라는 함수가 있습니다.
apply 함수는 이름 그대로 적용하겠다는 것입니다.
어떤 조건을 적용해서 데이터를 검색하겠다는 뜻입니다.

예:  이름의 첫번째 철자가 A 인 사원들의  이름을 출력하시오 !

emp[ ['ename'] ]   [  emp['ename'].apply(  적용할 검색 조건 )  ]  

emp[ ['ename'] ]   [  emp['ename'].apply(  lambda   x : x[0] =='A'  )  ]  
                                                   ADAMS :  'A' =='A'

lambda   x : x[0] =='A'   <--- 이 부분 설명

lambda  -->  이름이 없는 한줄 짜리 함수를 생성할 때 사용하는 키워드
             lambda 다음에 어떤 기능에 대한 코드를 적어주면 됩니다.

x : x[0]   --->    입력값을 받은 변수 :  출력을 하는 조건

x 에 뭐가 입력되냐면  emp['ename'] 의 데이터가 x 라는 변수에 입력됩니다.

emp['ename']   <--- 이것만 실행해보면  다음과 같이 이름이 출력되는데

아래의 이름 14개가 KING 부터 하나씩 x 라는 변수에 입력이 됩니다.  

0       KING          ---------------->   x  라는 빈컵 <br>
1      BLAKE        ---->  x  :  x[0]  --->  B<br>
2      CLARK       ---->   x : x[0]  --->  C <br>
3      JONES<br>
4     MARTIN<br>
5      ALLEN<br>
6     TURNER<br>
7      JAMES<br>
8       WARD<br>
9       FORD<br>
10     SMITH<br>
11     SCOTT<br>
12     ADAMS<br>
13    MILLER     ---->  x  :  x[0]    ---->  M <br>

x 라는 변수에  KING 이 제일 처음 담겼고   출력값으로 x[0] 이 실행되는데
x 다음에 나오는 [0] 을 인덱스라고 합니다.

'KING'[0]  이라고  수행한것 입니다.  

KING 이라는 문자열에서  0번째 철자를 가져오라는 뜻입니다.

파이썬은 1번부터 시작하지 않고 0번부터 시작합니다.

'KING'[0]    -->  K <br>
'KING'[1]    -->  I<br>
'KING'[2]   -->  N<br>
'KING'[3] ---->  G<br>

In [59]:
emp[ ['ename'] ]   [  emp['ename'].apply(  lambda   x : x[0] =='A'  )  ]

    ename
5   ALLEN
12  ADAMS

In [60]:
#문제19.  이름의 두번째 철자가 M 인 사원들의 이름을 출력하시오 !

#답:


emp[ ['ename'] ]   [  emp['ename'].apply(  lambda   x : x[1] =='M'  )  ]

    ename
10  SMITH

In [61]:
# 문제20.  이름의 끝글자가 T 로 끝나는 사원들의 이름과 월급을 출력하시오  !
emp[ ['ename'] ]   [  emp['ename'].apply(  lambda   x : x[-1] =='T'  )  ]

    ename
11  SCOTT

In [62]:
# ▩ 예제5.  데이터 정렬하기 !

#  * 이름와 월급을 출력하는데  월급이 높은 사원부터 출력하시오 !

# Pandas>  emp[ ['ename', 'sal'] ].sort_values( by ='sal',  ascending=False)

# 문법:    판다스 데이터프레임(또는 시리즈).sort_values( by='정렬할 컬럼' , ascending=True)
#                                                                                               ascending= True 또는 False)

#  True 와 False 를 쓸때는 T 와 F 를 대문자로 해주셔야합니다.

In [63]:
emp[ ['ename', 'sal'] ].sort_values( by ='sal',  ascending=True)

     ename   sal
10   SMITH   800
7    JAMES   950
12   ADAMS  1100
4   MARTIN  1250
8     WARD  1250
13  MILLER  1300
6   TURNER  1500
5    ALLEN  1600
2    CLARK  2450
1    BLAKE  2850
3    JONES  2975
11   SCOTT  3000
9     FORD  3000
0     KING  5000

In [64]:
# 문제23.  직업이 SALESMAN 인 사원들의  이름과 월급과 직업을 출력하는데
# 월급이 높은 사원부터 출력하시오 !


emp[['ename', 'sal', 'job'] ] [ emp['job']=='SALESMAN'].sort_values(by='sal', ascending=False)

    ename   sal       job
5   ALLEN  1600  SALESMAN
6  TURNER  1500  SALESMAN
4  MARTIN  1250  SALESMAN
8    WARD  1250  SALESMAN